version: '3.8'
services:
    autospotting:
        build:
          context: .
          dockerfile: Dockerfile.build
          args:
            flavor: nightly
        environment:
          - AWS_ACCESS_KEY_ID
          - AWS_SECRET_ACCESS_KEY
          - AWS_SESSION_TOKEN
        entrypoint:
          - ./AutoSpotting
        volumes:
          - type: bind
            source: ./build
            target: /src/build
