version: '3.2'
services:
    autospotting:
        build:
          context: .
          dockerfile: Dockerfile-build
        environment:
        - FLAVOR=nightly
        - CGO_ENABLED=0
        - COVERALLS_TOKEN
        entrypoint:
          - make
          - travisci
        volumes:
          - type: bind
            source: ./build
            target: /src/build
