---
# Note: this is just an example on how the stack can be executed in a test
# setting, you may want to change it for your production use case.

# This file is handled automatically using the clouds-aws tool. It can be
# installed using pip, or from https://github.com/elias5000/clouds-aws. The same
# values can be passed manually when you run the stack from the AWS console.

# DeployRegionalResourcesStackSet: 'true'
# SQSQueueName: AutoSpotting.fifo

# Default value: rate(5 minutes)
ExecutionFrequency: rate(1 minute)

# Tag to be applied on the Lambda function
LambdaFunctionTagKey: Name
LambdaFunctionTagValue: autospotting

# You may need to change this on large installations if you run into out of
# memory situations.
LambdaMemorySize: '1024'

# Default value: 0
MinOnDemandNumber: '0'

# Valid choices:
# - for EC2 Classic environments: Linux/UNIX | SUSE Linux | Windows
# - for VPC: Linux/UNIX (Amazon VPC) | SUSE Linux (Amazon VPC) |
#   Windows (Amazon VPC)
SpotProductDescription: Linux/UNIX (Amazon VPC)

# Valid choices: opt-in (default), opt-out
TagFilteringMode: opt-out
